import express from 'express'; import Order from '../models/Order.js'; import Product from '../models/Product.js'; import {auth,admin} from '../middleware/auth.js';
const r=express.Router();
const number=()=>`THX-${Date.now().toString().slice(-8)}-${Math.floor(Math.random()*90+10)}`;
r.post('/',auth,async(req,res)=>{try{const {items,shippingAddress,paymentMethod='COD',coupon=''}=req.body;if(!items?.length)return res.status(400).json({message:'Cart is empty'});let subtotal=0,clean=[];for(const i of items){const p=await Product.findById(i.product);if(!p||!p.active)return res.status(400).json({message:'A product is unavailable'});if(p.stock<i.quantity)return res.status(400).json({message:`Only ${p.stock} left for ${p.name}`});subtotal+=p.price*i.quantity;clean.push({product:p._id,name:p.name,image:p.images?.[0],price:p.price,quantity:i.quantity})}const discount=coupon?.toUpperCase()==='THIRANEX10'?Math.round(subtotal*.1*100)/100:0;const shipping=subtotal-discount>=999?0:79;const total=subtotal-discount+shipping;const o=await Order.create({user:req.user.id,items:clean,shippingAddress,paymentMethod,paymentStatus:paymentMethod==='COD'?'Pending':'Paid',subtotal,shipping,discount,total,orderNumber:number()});for(const i of clean)await Product.findByIdAndUpdate(i.product,{$inc:{stock:-i.quantity}});res.status(201).json({order:o})}catch(e){res.status(500).json({message:e.message})}});
r.get('/mine',auth,async(req,res)=>res.json({orders:await Order.find({user:req.user.id}).sort('-createdAt')}));
r.get('/:id',auth,async(req,res)=>{const q=req.user.role==='admin'?{_id:req.params.id}:{_id:req.params.id,user:req.user.id};const o=await Order.findOne(q);if(!o)return res.status(404).json({message:'Order not found'});res.json({order:o})});
r.get('/',auth,admin,async(req,res)=>res.json({orders:await Order.find().populate('user','name email').sort('-createdAt')}));
r.put('/:id/status',auth,admin,async(req,res)=>{const allowed=['Processing','Confirmed','Shipped','Out for delivery','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid status'});const o=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});res.json({order:o})});
export default r;
